#!/bin/bash

#################
# Arch packages #
#################

# Install packages on Arch Linux
echo "Installing trizen"
pacman -S trizen

##########
# Neovim #
##########
# Install neovim python3 package with pip
if command -v pip3 >/dev/null 2>&1; then
    echo "Installing neovim python package"
    pip3 install neovim
fi

#######
# ZSH #
#######

# install zgen plugin manager
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

# Install the nerd-patched Hack font
if command -v git >/dev/null 2>&1; then
    git clone git@github.com:ryanoasis/nerd-fonts.git
    cd nerd-fonts
    sudo chmod a+x install.sh && ./install.sh Hack
    cd .. && rm -rf nerd-fonts
fi

