#!/bin/zsh

##########
# iTerm2 #
##########

# Specify the preferences directory
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.config/iterm2"
# Tell iTerm2 to use the custom preferences in the directory
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

############
# Homebrew #
############

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    curl -fsSL https://rawgit.com/kube/42homebrew/master/install.sh | zsh
fi

# Install all brew packages
if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
fi

##########
# Neovim #
##########

# Install neovim python3 package with pip
if command -v pip3 >/dev/null 2>&1; then
    echo "Installing neovim python package"
    pip3 install neovim
fi

#######
# ZSH #
#######

# install zgen plugin manager
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

chsh -s =zsh

#######
# FZF #
#######

# install key bindings and fuzzy completion
$(brew --prefix)/opt/fzf/install
